version: "3"

services:
  bansosman:
    build: .
    restart: "no"
    ports:
      - 8005:8080

  mysql-bansosman:
    image: mariadb:10.1
    hostname: mysql.docker
    command: --init-file /app/config/init.sql
    volumes:
      - ./init.sql:/app/config/init.sql
    environment:
      MYSQL_DATABASE: bansosman
      MYSQL_USER: root
    ports:
      - 3336:3306
    restart: "no"
