// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	apbn "bansosman/bussiness/apbn"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: apbns, id
func (_m *Repository) Delete(apbns *apbn.Domain, id int) (string, error) {
	ret := _m.Called(apbns, id)

	var r0 string
	if rf, ok := ret.Get(0).(func(*apbn.Domain, int) string); ok {
		r0 = rf(apbns, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*apbn.Domain, int) error); ok {
		r1 = rf(apbns, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *Repository) FindAll() ([]apbn.Domain, error) {
	ret := _m.Called()

	var r0 []apbn.Domain
	if rf, ok := ret.Get(0).(func() []apbn.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]apbn.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *Repository) FindByID(id int) (*apbn.Domain, error) {
	ret := _m.Called(id)

	var r0 *apbn.Domain
	if rf, ok := ret.Get(0).(func(int) *apbn.Domain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apbn.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: apbns
func (_m *Repository) Insert(apbns *apbn.Domain) (*apbn.Domain, error) {
	ret := _m.Called(apbns)

	var r0 *apbn.Domain
	if rf, ok := ret.Get(0).(func(*apbn.Domain) *apbn.Domain); ok {
		r0 = rf(apbns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apbn.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*apbn.Domain) error); ok {
		r1 = rf(apbns)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: apbns, id
func (_m *Repository) Update(apbns *apbn.Domain, id int) (*apbn.Domain, error) {
	ret := _m.Called(apbns, id)

	var r0 *apbn.Domain
	if rf, ok := ret.Get(0).(func(*apbn.Domain, int) *apbn.Domain); ok {
		r0 = rf(apbns, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apbn.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*apbn.Domain, int) error); ok {
		r1 = rf(apbns, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
